### ISSUE TITLE
YTImport.vb issue

### ISSUE THREAD

**Issue by JesWhite** [maggot99999/source-live-audio-mixer#5]
i want to import from youtube and there is a problem from logs.

> System.Collections.Generic.KeyNotFoundException: Verilen anahtar sözlükte yoktu.
   konum: VideoLibrary.Helpers.Query.get_Item(String key)
   konum: VideoLibrary.YouTube.Unscramble(String queryString)
   konum: System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   konum: VideoLibrary.YouTube.<ParseVideos>d__6.MoveNext()
   konum: System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   konum: VideoLibrary.ServiceBase`1.VideoSelector(IEnumerable`1 videos)
   konum: VideoLibrary.ServiceBase`1.<GetVideoAsync>d__6.MoveNext()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: VideoLibrary.ServiceBase`1.<GetVideoAsync>d__5.MoveNext()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: VideoLibrary.ServiceBase`1.GetVideo(String videoUri)
   konum: SLAM.YTImport.DownloadWorker_DoWork(Object sender, DoWorkEventArgs e) G:\Projects\source-live-audio-mixer\SLAM\YTImport.vb içinde: satır 46

>

**Comment by Hackmastr** [comment]
Hello,

What version are you running?
Also, mind showing me the video? Is it age restricted?

**Comment by JesWhite** [comment]
> Hello,
> 
> What version are you running?
> Also, mind showing me the video? Is it age restricted?

last version.
1.6.1 youtube import problem...

**Comment by Shock95x** [comment]
Apparently you have to update libvideo to 3.0 but even then I get another error.

**Comment by drewfatstacks** [comment]
After updating to libvideo.dll 3.0 I am receiving this error in the errorlog now:

`--------------------3/11/2020 10:35:15 PM UTC--------------------
System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at VideoLibrary.YouTube.ParseVideos(String source)
   at VideoLibrary.YouTube.<GetAllVideosAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at VideoLibrary.ServiceBase`1.<GetVideoAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at VideoLibrary.ServiceBase`1.<GetVideoAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VideoLibrary.ServiceBase`1.GetVideo(String videoUri)
   at SLAM.YTImport.DownloadWorker_DoWork(Object sender, DoWorkEventArgs e) in G:\Projects\source-live-audio-mixer\SLAM\YTImport.vb:line 49

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

`

**Comment by xTheEc0** [comment]
Just cloned, updated _all_nuget packages, built (disabled signing) and youtube downloading started working for me.

**Comment by CodenameOccasus** [comment]
I cloned it, updated all the shit, and built. works good but needs released again functioning @Hackmastr

**Comment by JesWhite** [comment]
> I cloned it, updated all the shit, and built. works good but needs released again functioning @Hackmastr

oh i tried to download from youtube again but not worked on 1.6.2

**Comment by Hackmastr** [comment]
Pushed new update. Please try and let me know!

**Comment by CodenameOccasus** [comment]
Will do today or tomorrow

**Comment by drewfatstacks** [comment]
> 
> 
> Pushed new update. Please try and let me know!

Can confirm the newest update works fine with YouTube import.  Thanks.

**Comment by JesWhite** [comment]
1.7.0 working fine... 
ty for update.
https://github.com/maggot99999/source-live-audio-mixer/releases/tag/1.7.0
